// FILE: pubspec.yaml
name: vlc_clone_sample
description: VLC-style media player sample (Flutter + Provider + Hive + video_player + just_audio)
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: 
  hive: 
  hive_flutter: 
  path_provider: 
  permission_handler: 
  video_player: 
  just_audio: 
  file_picker: 
  video_thumbnail: 
  intl: 
  screen_brightness: ^2.1.7
  flutter_volume_controller: ^1.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    # - assets/icons/
    # - assets/sample_media/
