// FILE: pubspec.yaml
name: vlc_clone_sample
description: JK Wave - Feature-rich media player (Flutter + Provider + Hive + video_player + just_audio)
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: 
  hive: 
  hive_flutter: 
  path_provider: 
  permission_handler: 
  video_player: 
  just_audio: 
  media_kit: ^1.0.0
  media_kit_video: ^1.0.0
  media_kit_libs_android_video: ^1.0.0 
  file_picker: 
  video_thumbnail: 
  intl: 
  screen_brightness: ^2.1.7
  flutter_volume_controller: ^1.0.0 
  package_info_plus: ^8.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  hive_generator: ^2.0.0
  flutter_native_splash: ^2.2.12
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    # - assets/sample_media/

flutter_native_splash:
  color: "#000000"
  image: assets/Picsart_25-12-04_18-05-58-416.png
  android_12:
    image: assets/Picsart_25-12-04_18-05-58-416.png
    color: "#000000"
  ios: true
  web: false

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Picsart_25-12-04_18-05-58-416.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/Picsart_25-12-04_18-05-58-416.png"
